// Author: Mohammad Noormohammadpour
// Copyright 2019
// Can be distributed under MIT license (https://opensource.org/licenses/MIT)

#ifndef TOPOLOGIES_HPP
#define TOPOLOGIES_HPP

#include <vector>
#include <map>
#include <unordered_map>
#include <unordered_set>

#include "topology.hpp"

using namespace std;

namespace Network {

Topology* BuildTopologyANS() {
  const int Nodes = 18;
  Topology* topo = new Topology(Nodes, "ANS");
  topo->AddBidirectionalEdge(topo->GetNode(0),  topo->GetNode(1),  1);
  topo->AddBidirectionalEdge(topo->GetNode(0),  topo->GetNode(3),  1);
  topo->AddBidirectionalEdge(topo->GetNode(1),  topo->GetNode(3),  1);
  topo->AddBidirectionalEdge(topo->GetNode(1),  topo->GetNode(6),  1);
  topo->AddBidirectionalEdge(topo->GetNode(1),  topo->GetNode(7),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),  topo->GetNode(3),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),  topo->GetNode(9),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),  topo->GetNode(11), 1);
  topo->AddBidirectionalEdge(topo->GetNode(4),  topo->GetNode(5),  1);
  topo->AddBidirectionalEdge(topo->GetNode(4),  topo->GetNode(6),  1);
  topo->AddBidirectionalEdge(topo->GetNode(5),  topo->GetNode(17), 1);
  topo->AddBidirectionalEdge(topo->GetNode(6),  topo->GetNode(7),  1);
  topo->AddBidirectionalEdge(topo->GetNode(7),  topo->GetNode(8),  1);
  topo->AddBidirectionalEdge(topo->GetNode(7),  topo->GetNode(9),  1);
  topo->AddBidirectionalEdge(topo->GetNode(8),  topo->GetNode(9),  1);
  topo->AddBidirectionalEdge(topo->GetNode(8),  topo->GetNode(13), 1);
  topo->AddBidirectionalEdge(topo->GetNode(8),  topo->GetNode(17), 1);
  topo->AddBidirectionalEdge(topo->GetNode(10), topo->GetNode(11), 1);
  topo->AddBidirectionalEdge(topo->GetNode(10), topo->GetNode(12), 1);
  topo->AddBidirectionalEdge(topo->GetNode(11), topo->GetNode(12), 1);
  topo->AddBidirectionalEdge(topo->GetNode(12), topo->GetNode(13), 1);
  topo->AddBidirectionalEdge(topo->GetNode(12), topo->GetNode(14), 1);
  topo->AddBidirectionalEdge(topo->GetNode(14), topo->GetNode(15), 1);
  topo->AddBidirectionalEdge(topo->GetNode(15), topo->GetNode(16), 1);
  topo->AddBidirectionalEdge(topo->GetNode(15), topo->GetNode(17), 1);
  return topo;
}

Topology* BuildTopologyGEANT2009() {
  const int Nodes = 34;
  Topology* topo = new Topology(Nodes, "GEANT2009");
  topo->AddBidirectionalEdge(topo->GetNode(0),   topo->GetNode(1),   1);
  topo->AddBidirectionalEdge(topo->GetNode(0),   topo->GetNode(2),   1);
  topo->AddBidirectionalEdge(topo->GetNode(0),   topo->GetNode(4),   1);
  topo->AddBidirectionalEdge(topo->GetNode(0),   topo->GetNode(13),  0.0045);
  topo->AddBidirectionalEdge(topo->GetNode(1),   topo->GetNode(28),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(32),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(4),   1);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(25),  0.25);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(26),  0.031);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(29),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(30),  1);
  topo->AddBidirectionalEdge(topo->GetNode(3),   topo->GetNode(24),  1);
  topo->AddBidirectionalEdge(topo->GetNode(3),   topo->GetNode(4),   1);
  topo->AddBidirectionalEdge(topo->GetNode(3),   topo->GetNode(5),   1);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(5),   1);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(6),   1);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(8),   1);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(12),  0.25);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(25),  0.25);
  topo->AddBidirectionalEdge(topo->GetNode(5),   topo->GetNode(17),  1);
  topo->AddBidirectionalEdge(topo->GetNode(6),   topo->GetNode(7),   1);
  topo->AddBidirectionalEdge(topo->GetNode(7),   topo->GetNode(8),   1);
  topo->AddBidirectionalEdge(topo->GetNode(7),   topo->GetNode(19),  1);
  topo->AddBidirectionalEdge(topo->GetNode(7),   topo->GetNode(28),  1);
  topo->AddBidirectionalEdge(topo->GetNode(8),   topo->GetNode(9),   1);
  topo->AddBidirectionalEdge(topo->GetNode(8),   topo->GetNode(19),  1);
  topo->AddBidirectionalEdge(topo->GetNode(9),   topo->GetNode(10),  1);
  topo->AddBidirectionalEdge(topo->GetNode(9),   topo->GetNode(11),  0.0155);
  topo->AddBidirectionalEdge(topo->GetNode(9),   topo->GetNode(13),  0.0045);
  topo->AddBidirectionalEdge(topo->GetNode(9),   topo->GetNode(19),  1);
  topo->AddBidirectionalEdge(topo->GetNode(9),   topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(11),  0.0155);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(20),  1);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(14),  topo->GetNode(20),  0.25);
  topo->AddBidirectionalEdge(topo->GetNode(14),  topo->GetNode(15),  0.25);
  topo->AddBidirectionalEdge(topo->GetNode(15),  topo->GetNode(16),  1);
  topo->AddBidirectionalEdge(topo->GetNode(15),  topo->GetNode(20),  1);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(17),  1);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(20),  1);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(21),  1);
  topo->AddBidirectionalEdge(topo->GetNode(17),  topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(19),  1);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(28),  0.25);
  topo->AddBidirectionalEdge(topo->GetNode(21),  topo->GetNode(22),  1);
  topo->AddBidirectionalEdge(topo->GetNode(22),  topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(24),  topo->GetNode(33),  1);
  topo->AddBidirectionalEdge(topo->GetNode(27),  topo->GetNode(28),  1);
  topo->AddBidirectionalEdge(topo->GetNode(29),  topo->GetNode(30),  1);
  topo->AddBidirectionalEdge(topo->GetNode(30),  topo->GetNode(31),  1);
  topo->AddBidirectionalEdge(topo->GetNode(32),  topo->GetNode(33),  1);
  return topo;
}

Topology* BuildTopologyGSCALE() {
  const int Nodes = 12;
  Topology* topo = new Topology(Nodes, "GSCALE");
  topo->AddBidirectionalEdge(topo->GetNode(0),  topo->GetNode(1),  1);
  topo->AddBidirectionalEdge(topo->GetNode(1),  topo->GetNode(2),  1);
  topo->AddBidirectionalEdge(topo->GetNode(0),  topo->GetNode(4),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),  topo->GetNode(3),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),  topo->GetNode(5),  1);
  topo->AddBidirectionalEdge(topo->GetNode(3),  topo->GetNode(4),  1);
  topo->AddBidirectionalEdge(topo->GetNode(4),  topo->GetNode(5),  1);
  topo->AddBidirectionalEdge(topo->GetNode(5),  topo->GetNode(7),  1);
  topo->AddBidirectionalEdge(topo->GetNode(3),  topo->GetNode(6),  1);
  topo->AddBidirectionalEdge(topo->GetNode(3),  topo->GetNode(7),  1);
  topo->AddBidirectionalEdge(topo->GetNode(5),  topo->GetNode(6),  1);
  topo->AddBidirectionalEdge(topo->GetNode(6),  topo->GetNode(7),  1);
  topo->AddBidirectionalEdge(topo->GetNode(8),  topo->GetNode(10), 1);
  topo->AddBidirectionalEdge(topo->GetNode(8),  topo->GetNode(9),  1);
  topo->AddBidirectionalEdge(topo->GetNode(9),  topo->GetNode(10), 1);
  topo->AddBidirectionalEdge(topo->GetNode(7),  topo->GetNode(9),  1);
  topo->AddBidirectionalEdge(topo->GetNode(6),  topo->GetNode(10), 1);
  topo->AddBidirectionalEdge(topo->GetNode(9),  topo->GetNode(11), 1);
  topo->AddBidirectionalEdge(topo->GetNode(10), topo->GetNode(11), 1);
  return topo;
}

Topology* BuildTopologyUNINETT2011() {
  const int Nodes = 69;
  Topology* topo = new Topology(Nodes, "UNINETT2011");
  topo->AddBidirectionalEdge(topo->GetNode( 0),  topo->GetNode( 1), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 0),  topo->GetNode( 3), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 0),  topo->GetNode(68), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 0),  topo->GetNode(49), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 0),  topo->GetNode(54), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 0),  topo->GetNode(23), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 1),  topo->GetNode(32), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 1),  topo->GetNode( 3), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 1),  topo->GetNode( 6), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 1),  topo->GetNode(48), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 1),  topo->GetNode(58), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 1),  topo->GetNode(62), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 2),  topo->GetNode( 3), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 2),  topo->GetNode(60), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 3),  topo->GetNode( 5), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 3),  topo->GetNode(45), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 3),  topo->GetNode(46), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode( 3),  topo->GetNode(22), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode( 3),  topo->GetNode(61), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode( 4),  topo->GetNode( 5), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 4),  topo->GetNode( 7), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 5),  topo->GetNode(10), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 5),  topo->GetNode(54), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 6),  topo->GetNode(51), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 7),  topo->GetNode(51), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 8),  topo->GetNode(65), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 8),  topo->GetNode(36), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 8),  topo->GetNode(37), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode( 8),  topo->GetNode( 9), 0.0031);
  topo->AddBidirectionalEdge(topo->GetNode( 8),  topo->GetNode(29), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode( 8),  topo->GetNode(62), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode( 9),  topo->GetNode(26), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(50), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(11), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(32), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(15), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(29), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(61), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(13), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(13),  topo->GetNode(40), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(13),  topo->GetNode(43), 1.0000);
  topo->AddBidirectionalEdge(topo->GetNode(13),  topo->GetNode(29), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode(14),  topo->GetNode(30), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(14),  topo->GetNode(31), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(15),  topo->GetNode(42), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(15),  topo->GetNode(43), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(17), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(61), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(22), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(39), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(17),  topo->GetNode(25), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(19), 0.0031);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(20), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(46), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(23), 0.2273);
  topo->AddBidirectionalEdge(topo->GetNode(20),  topo->GetNode(21), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(21),  topo->GetNode(22), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(22),  topo->GetNode(23), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(22),  topo->GetNode(24), 0.0031);
  topo->AddBidirectionalEdge(topo->GetNode(22),  topo->GetNode(61), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(24),  topo->GetNode(25), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(25),  topo->GetNode(38), 0.0031);
  topo->AddBidirectionalEdge(topo->GetNode(26),  topo->GetNode(61), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(26),  topo->GetNode(29), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(27),  topo->GetNode(35), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(27),  topo->GetNode(36), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(27),  topo->GetNode(61), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(28),  topo->GetNode(32), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(30),  topo->GetNode(56), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(31),  topo->GetNode(44), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(33),  topo->GetNode(40), 0.0141);
  topo->AddBidirectionalEdge(topo->GetNode(34),  topo->GetNode(35), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(34),  topo->GetNode(62), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(39),  topo->GetNode(41), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(41),  topo->GetNode(63), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(42),  topo->GetNode(56), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(42),  topo->GetNode(44), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(43),  topo->GetNode(56), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(43),  topo->GetNode(62), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(46),  topo->GetNode(47), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(47),  topo->GetNode(53), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(48),  topo->GetNode(50), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(49),  topo->GetNode(50), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(52),  topo->GetNode(54), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(53),  topo->GetNode(54), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(54),  topo->GetNode(55), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(57),  topo->GetNode(64), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(57),  topo->GetNode(66), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(59),  topo->GetNode(67), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(59),  topo->GetNode(60), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(61),  topo->GetNode(62), 0.9091);
  topo->AddBidirectionalEdge(topo->GetNode(61),  topo->GetNode(63), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(62),  topo->GetNode(63), 0.1818);
  topo->AddBidirectionalEdge(topo->GetNode(63),  topo->GetNode(64), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(66),  topo->GetNode(67), 0.0909);
  topo->AddBidirectionalEdge(topo->GetNode(67),  topo->GetNode(68), 0.0909);
  return topo;
}

Topology* BuildTopologyCOGENT() {
  const int Nodes = 197;
  Topology* topo = new Topology(Nodes, "COGENT");
  topo->AddBidirectionalEdge(topo->GetNode(0),   topo->GetNode(176), 1);
  topo->AddBidirectionalEdge(topo->GetNode(0),   topo->GetNode(9),   1);
  topo->AddBidirectionalEdge(topo->GetNode(1),   topo->GetNode(114), 1);
  topo->AddBidirectionalEdge(topo->GetNode(1),   topo->GetNode(116), 1);
  topo->AddBidirectionalEdge(topo->GetNode(1),   topo->GetNode(175), 1);
  topo->AddBidirectionalEdge(topo->GetNode(1),   topo->GetNode(176), 1);
  topo->AddBidirectionalEdge(topo->GetNode(1),   topo->GetNode(8),   1);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(11),  1);
  topo->AddBidirectionalEdge(topo->GetNode(10),  topo->GetNode(13),  1);
  topo->AddBidirectionalEdge(topo->GetNode(100), topo->GetNode(132), 1);
  topo->AddBidirectionalEdge(topo->GetNode(100), topo->GetNode(99),  1);
  topo->AddBidirectionalEdge(topo->GetNode(101), topo->GetNode(102), 1);
  topo->AddBidirectionalEdge(topo->GetNode(101), topo->GetNode(104), 1);
  topo->AddBidirectionalEdge(topo->GetNode(101), topo->GetNode(180), 1);
  topo->AddBidirectionalEdge(topo->GetNode(102), topo->GetNode(109), 1);
  topo->AddBidirectionalEdge(topo->GetNode(103), topo->GetNode(104), 1);
  topo->AddBidirectionalEdge(topo->GetNode(103), topo->GetNode(106), 1);
  topo->AddBidirectionalEdge(topo->GetNode(105), topo->GetNode(106), 1);
  topo->AddBidirectionalEdge(topo->GetNode(105), topo->GetNode(107), 1);
  topo->AddBidirectionalEdge(topo->GetNode(105), topo->GetNode(179), 1);
  topo->AddBidirectionalEdge(topo->GetNode(107), topo->GetNode(108), 1);
  topo->AddBidirectionalEdge(topo->GetNode(107), topo->GetNode(129), 1);
  topo->AddBidirectionalEdge(topo->GetNode(108), topo->GetNode(179), 1);
  topo->AddBidirectionalEdge(topo->GetNode(109), topo->GetNode(110), 1);
  topo->AddBidirectionalEdge(topo->GetNode(11),  topo->GetNode(16),  1);
  topo->AddBidirectionalEdge(topo->GetNode(110), topo->GetNode(128), 1);
  topo->AddBidirectionalEdge(topo->GetNode(111), topo->GetNode(112), 1);
  topo->AddBidirectionalEdge(topo->GetNode(111), topo->GetNode(140), 1);
  topo->AddBidirectionalEdge(topo->GetNode(112), topo->GetNode(137), 1);
  topo->AddBidirectionalEdge(topo->GetNode(113), topo->GetNode(114), 1);
  topo->AddBidirectionalEdge(topo->GetNode(113), topo->GetNode(191), 1);
  topo->AddBidirectionalEdge(topo->GetNode(115), topo->GetNode(116), 1);
  topo->AddBidirectionalEdge(topo->GetNode(115), topo->GetNode(118), 1);
  topo->AddBidirectionalEdge(topo->GetNode(117), topo->GetNode(118), 1);
  topo->AddBidirectionalEdge(topo->GetNode(117), topo->GetNode(120), 1);
  topo->AddBidirectionalEdge(topo->GetNode(119), topo->GetNode(175), 1);
  topo->AddBidirectionalEdge(topo->GetNode(119), topo->GetNode(176), 1);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(13),  1);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(30),  1);
  topo->AddBidirectionalEdge(topo->GetNode(12),  topo->GetNode(32),  1);
  topo->AddBidirectionalEdge(topo->GetNode(120), topo->GetNode(175), 1);
  topo->AddBidirectionalEdge(topo->GetNode(121), topo->GetNode(122), 1);
  topo->AddBidirectionalEdge(topo->GetNode(121), topo->GetNode(124), 1);
  topo->AddBidirectionalEdge(topo->GetNode(122), topo->GetNode(61),  1);
  topo->AddBidirectionalEdge(topo->GetNode(123), topo->GetNode(124), 1);
  topo->AddBidirectionalEdge(topo->GetNode(123), topo->GetNode(125), 1);
  topo->AddBidirectionalEdge(topo->GetNode(123), topo->GetNode(126), 1);
  topo->AddBidirectionalEdge(topo->GetNode(127), topo->GetNode(128), 1);
  topo->AddBidirectionalEdge(topo->GetNode(127), topo->GetNode(130), 1);
  topo->AddBidirectionalEdge(topo->GetNode(128), topo->GetNode(61),  1);
  topo->AddBidirectionalEdge(topo->GetNode(129), topo->GetNode(130), 1);
  topo->AddBidirectionalEdge(topo->GetNode(129), topo->GetNode(14),  1);
  topo->AddBidirectionalEdge(topo->GetNode(13),  topo->GetNode(15),  1);
  topo->AddBidirectionalEdge(topo->GetNode(13),  topo->GetNode(16),  1);
  topo->AddBidirectionalEdge(topo->GetNode(131), topo->GetNode(142), 1);
  topo->AddBidirectionalEdge(topo->GetNode(131), topo->GetNode(5),   1);
  topo->AddBidirectionalEdge(topo->GetNode(131), topo->GetNode(98),  1);
  topo->AddBidirectionalEdge(topo->GetNode(132), topo->GetNode(135), 1);
  topo->AddBidirectionalEdge(topo->GetNode(133), topo->GetNode(173), 1);
  topo->AddBidirectionalEdge(topo->GetNode(133), topo->GetNode(77),  1);
  topo->AddBidirectionalEdge(topo->GetNode(134), topo->GetNode(135), 1);
  topo->AddBidirectionalEdge(topo->GetNode(134), topo->GetNode(137), 1);
  topo->AddBidirectionalEdge(topo->GetNode(134), topo->GetNode(138), 1);
  topo->AddBidirectionalEdge(topo->GetNode(135), topo->GetNode(4),   1);
  topo->AddBidirectionalEdge(topo->GetNode(136), topo->GetNode(139), 1);
  topo->AddBidirectionalEdge(topo->GetNode(137), topo->GetNode(172), 1);
  topo->AddBidirectionalEdge(topo->GetNode(138), topo->GetNode(141), 1);
  topo->AddBidirectionalEdge(topo->GetNode(138), topo->GetNode(174), 1);
  topo->AddBidirectionalEdge(topo->GetNode(139), topo->GetNode(174), 1);
  topo->AddBidirectionalEdge(topo->GetNode(14),  topo->GetNode(15),  1);
  topo->AddBidirectionalEdge(topo->GetNode(14),  topo->GetNode(64),  1);
  topo->AddBidirectionalEdge(topo->GetNode(140), topo->GetNode(141), 1);
  topo->AddBidirectionalEdge(topo->GetNode(142), topo->GetNode(143), 1);
  topo->AddBidirectionalEdge(topo->GetNode(143), topo->GetNode(185), 1);
  topo->AddBidirectionalEdge(topo->GetNode(143), topo->GetNode(42),  1);
  topo->AddBidirectionalEdge(topo->GetNode(144), topo->GetNode(149), 1);
  topo->AddBidirectionalEdge(topo->GetNode(144), topo->GetNode(62),  1);
  topo->AddBidirectionalEdge(topo->GetNode(144), topo->GetNode(69),  1);
  topo->AddBidirectionalEdge(topo->GetNode(145), topo->GetNode(157), 1);
  topo->AddBidirectionalEdge(topo->GetNode(146), topo->GetNode(152), 1);
  topo->AddBidirectionalEdge(topo->GetNode(146), topo->GetNode(154), 1);
  topo->AddBidirectionalEdge(topo->GetNode(147), topo->GetNode(166), 1);
  topo->AddBidirectionalEdge(topo->GetNode(147), topo->GetNode(177), 1);
  topo->AddBidirectionalEdge(topo->GetNode(147), topo->GetNode(49),  1);
  topo->AddBidirectionalEdge(topo->GetNode(148), topo->GetNode(154), 1);
  topo->AddBidirectionalEdge(topo->GetNode(148), topo->GetNode(83),  1);
  topo->AddBidirectionalEdge(topo->GetNode(148), topo->GetNode(84),  1);
  topo->AddBidirectionalEdge(topo->GetNode(149), topo->GetNode(150), 1);
  topo->AddBidirectionalEdge(topo->GetNode(149), topo->GetNode(63),  1);
  topo->AddBidirectionalEdge(topo->GetNode(150), topo->GetNode(82),  1);
  topo->AddBidirectionalEdge(topo->GetNode(150), topo->GetNode(89),  1);
  topo->AddBidirectionalEdge(topo->GetNode(151), topo->GetNode(152), 1);
  topo->AddBidirectionalEdge(topo->GetNode(152), topo->GetNode(153), 1);
  topo->AddBidirectionalEdge(topo->GetNode(152), topo->GetNode(77),  1);
  topo->AddBidirectionalEdge(topo->GetNode(153), topo->GetNode(154), 1);
  topo->AddBidirectionalEdge(topo->GetNode(153), topo->GetNode(160), 1);
  topo->AddBidirectionalEdge(topo->GetNode(154), topo->GetNode(159), 1);
  topo->AddBidirectionalEdge(topo->GetNode(154), topo->GetNode(183), 1);
  topo->AddBidirectionalEdge(topo->GetNode(155), topo->GetNode(156), 1);
  topo->AddBidirectionalEdge(topo->GetNode(155), topo->GetNode(165), 1);
  topo->AddBidirectionalEdge(topo->GetNode(155), topo->GetNode(195), 1);
  topo->AddBidirectionalEdge(topo->GetNode(155), topo->GetNode(48),  1);
  topo->AddBidirectionalEdge(topo->GetNode(156), topo->GetNode(157), 1);
  topo->AddBidirectionalEdge(topo->GetNode(157), topo->GetNode(158), 1);
  topo->AddBidirectionalEdge(topo->GetNode(158), topo->GetNode(165), 1);
  topo->AddBidirectionalEdge(topo->GetNode(158), topo->GetNode(183), 1);
  topo->AddBidirectionalEdge(topo->GetNode(158), topo->GetNode(196), 1);
  topo->AddBidirectionalEdge(topo->GetNode(16),  topo->GetNode(17),  1);
  topo->AddBidirectionalEdge(topo->GetNode(160), topo->GetNode(37),  1);
  topo->AddBidirectionalEdge(topo->GetNode(161), topo->GetNode(162), 1);
  topo->AddBidirectionalEdge(topo->GetNode(162), topo->GetNode(163), 1);
  topo->AddBidirectionalEdge(topo->GetNode(162), topo->GetNode(167), 1);
  topo->AddBidirectionalEdge(topo->GetNode(162), topo->GetNode(77),  1);
  topo->AddBidirectionalEdge(topo->GetNode(163), topo->GetNode(164), 1);
  topo->AddBidirectionalEdge(topo->GetNode(163), topo->GetNode(187), 1);
  topo->AddBidirectionalEdge(topo->GetNode(164), topo->GetNode(45),  1);
  topo->AddBidirectionalEdge(topo->GetNode(165), topo->GetNode(177), 1);
  topo->AddBidirectionalEdge(topo->GetNode(165), topo->GetNode(181), 1);
  topo->AddBidirectionalEdge(topo->GetNode(165), topo->GetNode(184), 1);
  topo->AddBidirectionalEdge(topo->GetNode(165), topo->GetNode(186), 1);
  topo->AddBidirectionalEdge(topo->GetNode(165), topo->GetNode(49),  1);
  topo->AddBidirectionalEdge(topo->GetNode(166), topo->GetNode(170), 1);
  topo->AddBidirectionalEdge(topo->GetNode(166), topo->GetNode(183), 1);
  topo->AddBidirectionalEdge(topo->GetNode(167), topo->GetNode(168), 1);
  topo->AddBidirectionalEdge(topo->GetNode(168), topo->GetNode(169), 1);
  topo->AddBidirectionalEdge(topo->GetNode(169), topo->GetNode(185), 1);
  topo->AddBidirectionalEdge(topo->GetNode(171), topo->GetNode(25),  1);
  topo->AddBidirectionalEdge(topo->GetNode(171), topo->GetNode(94),  1);
  topo->AddBidirectionalEdge(topo->GetNode(171), topo->GetNode(95),  1);
  topo->AddBidirectionalEdge(topo->GetNode(172), topo->GetNode(90),  1);
  topo->AddBidirectionalEdge(topo->GetNode(172), topo->GetNode(97),  1);
  topo->AddBidirectionalEdge(topo->GetNode(173), topo->GetNode(75),  1);
  topo->AddBidirectionalEdge(topo->GetNode(173), topo->GetNode(76),  1);
  topo->AddBidirectionalEdge(topo->GetNode(174), topo->GetNode(7),   1);
  topo->AddBidirectionalEdge(topo->GetNode(177), topo->GetNode(49),  1);
  topo->AddBidirectionalEdge(topo->GetNode(178), topo->GetNode(179), 1);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(19),  1);
  topo->AddBidirectionalEdge(topo->GetNode(18),  topo->GetNode(30),  1);
  topo->AddBidirectionalEdge(topo->GetNode(181), topo->GetNode(196), 1);
  topo->AddBidirectionalEdge(topo->GetNode(181), topo->GetNode(39),  1);
  topo->AddBidirectionalEdge(topo->GetNode(181), topo->GetNode(48),  1);
  topo->AddBidirectionalEdge(topo->GetNode(182), topo->GetNode(189), 1);
  topo->AddBidirectionalEdge(topo->GetNode(183), topo->GetNode(184), 1);
  topo->AddBidirectionalEdge(topo->GetNode(183), topo->GetNode(186), 1);
  topo->AddBidirectionalEdge(topo->GetNode(183), topo->GetNode(70),  1);
  topo->AddBidirectionalEdge(topo->GetNode(183), topo->GetNode(74),  1);
  topo->AddBidirectionalEdge(topo->GetNode(183), topo->GetNode(75),  1);
  topo->AddBidirectionalEdge(topo->GetNode(183), topo->GetNode(92),  1);
  topo->AddBidirectionalEdge(topo->GetNode(186), topo->GetNode(187), 1);
  topo->AddBidirectionalEdge(topo->GetNode(188), topo->GetNode(22),  1);
  topo->AddBidirectionalEdge(topo->GetNode(188), topo->GetNode(51),  1);
  topo->AddBidirectionalEdge(topo->GetNode(189), topo->GetNode(41),  1);
  topo->AddBidirectionalEdge(topo->GetNode(19),  topo->GetNode(68),  1);
  topo->AddBidirectionalEdge(topo->GetNode(19),  topo->GetNode(82),  1);
  topo->AddBidirectionalEdge(topo->GetNode(19),  topo->GetNode(89),  1);
  topo->AddBidirectionalEdge(topo->GetNode(190), topo->GetNode(191), 1);
  topo->AddBidirectionalEdge(topo->GetNode(191), topo->GetNode(8),   1);
  topo->AddBidirectionalEdge(topo->GetNode(192), topo->GetNode(193), 1);
  topo->AddBidirectionalEdge(topo->GetNode(193), topo->GetNode(194), 1);
  topo->AddBidirectionalEdge(topo->GetNode(194), topo->GetNode(8),   1);
  topo->AddBidirectionalEdge(topo->GetNode(194), topo->GetNode(98),  1);
  topo->AddBidirectionalEdge(topo->GetNode(195), topo->GetNode(196), 1);
  topo->AddBidirectionalEdge(topo->GetNode(196), topo->GetNode(38),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(76),  1);
  topo->AddBidirectionalEdge(topo->GetNode(2),   topo->GetNode(77),  1);
  topo->AddBidirectionalEdge(topo->GetNode(20),  topo->GetNode(21),  1);
  topo->AddBidirectionalEdge(topo->GetNode(20),  topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(21),  topo->GetNode(26),  1);
  topo->AddBidirectionalEdge(topo->GetNode(22),  topo->GetNode(23),  1);
  topo->AddBidirectionalEdge(topo->GetNode(24),  topo->GetNode(27),  1);
  topo->AddBidirectionalEdge(topo->GetNode(25),  topo->GetNode(55),  1);
  topo->AddBidirectionalEdge(topo->GetNode(26),  topo->GetNode(27),  1);
  topo->AddBidirectionalEdge(topo->GetNode(26),  topo->GetNode(28),  1);
  topo->AddBidirectionalEdge(topo->GetNode(26),  topo->GetNode(29),  1);
  topo->AddBidirectionalEdge(topo->GetNode(28),  topo->GetNode(51),  1);
  topo->AddBidirectionalEdge(topo->GetNode(28),  topo->GetNode(54),  1);
  topo->AddBidirectionalEdge(topo->GetNode(29),  topo->GetNode(78),  1);
  topo->AddBidirectionalEdge(topo->GetNode(3),   topo->GetNode(4),   1);
  topo->AddBidirectionalEdge(topo->GetNode(3),   topo->GetNode(77),  1);
  topo->AddBidirectionalEdge(topo->GetNode(30),  topo->GetNode(35),  1);
  topo->AddBidirectionalEdge(topo->GetNode(31),  topo->GetNode(37),  1);
  topo->AddBidirectionalEdge(topo->GetNode(32),  topo->GetNode(33),  1);
  topo->AddBidirectionalEdge(topo->GetNode(32),  topo->GetNode(37),  1);
  topo->AddBidirectionalEdge(topo->GetNode(34),  topo->GetNode(37),  1);
  topo->AddBidirectionalEdge(topo->GetNode(35),  topo->GetNode(37),  1);
  topo->AddBidirectionalEdge(topo->GetNode(36),  topo->GetNode(38),  1);
  topo->AddBidirectionalEdge(topo->GetNode(36),  topo->GetNode(39),  1);
  topo->AddBidirectionalEdge(topo->GetNode(37),  topo->GetNode(38),  1);
  topo->AddBidirectionalEdge(topo->GetNode(4),   topo->GetNode(6),   1);
  topo->AddBidirectionalEdge(topo->GetNode(40),  topo->GetNode(41),  1);
  topo->AddBidirectionalEdge(topo->GetNode(40),  topo->GetNode(42),  1);
  topo->AddBidirectionalEdge(topo->GetNode(41),  topo->GetNode(43),  1);
  topo->AddBidirectionalEdge(topo->GetNode(42),  topo->GetNode(43),  1);
  topo->AddBidirectionalEdge(topo->GetNode(44),  topo->GetNode(45),  1);
  topo->AddBidirectionalEdge(topo->GetNode(44),  topo->GetNode(47),  1);
  topo->AddBidirectionalEdge(topo->GetNode(45),  topo->GetNode(48),  1);
  topo->AddBidirectionalEdge(topo->GetNode(46),  topo->GetNode(47),  1);
  topo->AddBidirectionalEdge(topo->GetNode(46),  topo->GetNode(49),  1);
  topo->AddBidirectionalEdge(topo->GetNode(5),   topo->GetNode(6),   1);
  topo->AddBidirectionalEdge(topo->GetNode(50),  topo->GetNode(51),  1);
  topo->AddBidirectionalEdge(topo->GetNode(50),  topo->GetNode(57),  1);
  topo->AddBidirectionalEdge(topo->GetNode(52),  topo->GetNode(53),  1);
  topo->AddBidirectionalEdge(topo->GetNode(52),  topo->GetNode(55),  1);
  topo->AddBidirectionalEdge(topo->GetNode(53),  topo->GetNode(58),  1);
  topo->AddBidirectionalEdge(topo->GetNode(54),  topo->GetNode(55),  1);
  topo->AddBidirectionalEdge(topo->GetNode(56),  topo->GetNode(57),  1);
  topo->AddBidirectionalEdge(topo->GetNode(56),  topo->GetNode(59),  1);
  topo->AddBidirectionalEdge(topo->GetNode(58),  topo->GetNode(59),  1);
  topo->AddBidirectionalEdge(topo->GetNode(6),   topo->GetNode(7),   1);
  topo->AddBidirectionalEdge(topo->GetNode(60),  topo->GetNode(61),  1);
  topo->AddBidirectionalEdge(topo->GetNode(60),  topo->GetNode(69),  1);
  topo->AddBidirectionalEdge(topo->GetNode(62),  topo->GetNode(63),  1);
  topo->AddBidirectionalEdge(topo->GetNode(62),  topo->GetNode(86),  1);
  topo->AddBidirectionalEdge(topo->GetNode(63),  topo->GetNode(68),  1);
  topo->AddBidirectionalEdge(topo->GetNode(64),  topo->GetNode(65),  1);
  topo->AddBidirectionalEdge(topo->GetNode(64),  topo->GetNode(67),  1);
  topo->AddBidirectionalEdge(topo->GetNode(64),  topo->GetNode(68),  1);
  topo->AddBidirectionalEdge(topo->GetNode(65),  topo->GetNode(66),  1);
  topo->AddBidirectionalEdge(topo->GetNode(66),  topo->GetNode(67),  1);
  topo->AddBidirectionalEdge(topo->GetNode(67),  topo->GetNode(69),  1);
  topo->AddBidirectionalEdge(topo->GetNode(7),   topo->GetNode(8),   1);
  topo->AddBidirectionalEdge(topo->GetNode(70),  topo->GetNode(79),  1);
  topo->AddBidirectionalEdge(topo->GetNode(71),  topo->GetNode(72),  1);
  topo->AddBidirectionalEdge(topo->GetNode(71),  topo->GetNode(79),  1);
  topo->AddBidirectionalEdge(topo->GetNode(72),  topo->GetNode(73),  1);
  topo->AddBidirectionalEdge(topo->GetNode(73),  topo->GetNode(74),  1);
  topo->AddBidirectionalEdge(topo->GetNode(78),  topo->GetNode(79),  1);
  topo->AddBidirectionalEdge(topo->GetNode(78),  topo->GetNode(94),  1);
  topo->AddBidirectionalEdge(topo->GetNode(8),   topo->GetNode(9),   1);
  topo->AddBidirectionalEdge(topo->GetNode(80),  topo->GetNode(81),  1);
  topo->AddBidirectionalEdge(topo->GetNode(80),  topo->GetNode(86),  1);
  topo->AddBidirectionalEdge(topo->GetNode(80),  topo->GetNode(87),  1);
  topo->AddBidirectionalEdge(topo->GetNode(82),  topo->GetNode(83),  1);
  topo->AddBidirectionalEdge(topo->GetNode(82),  topo->GetNode(88),  1);
  topo->AddBidirectionalEdge(topo->GetNode(84),  topo->GetNode(85),  1);
  topo->AddBidirectionalEdge(topo->GetNode(86),  topo->GetNode(87),  1);
  topo->AddBidirectionalEdge(topo->GetNode(87),  topo->GetNode(88),  1);
  topo->AddBidirectionalEdge(topo->GetNode(91),  topo->GetNode(92),  1);
  topo->AddBidirectionalEdge(topo->GetNode(91),  topo->GetNode(99),  1);
  topo->AddBidirectionalEdge(topo->GetNode(92),  topo->GetNode(93),  1);
  topo->AddBidirectionalEdge(topo->GetNode(92),  topo->GetNode(96),  1);
  topo->AddBidirectionalEdge(topo->GetNode(95),  topo->GetNode(96),  1);
  topo->AddBidirectionalEdge(topo->GetNode(96),  topo->GetNode(97),  1);
  return topo;
}

} // namespace Network

#endif // TOPOLOGIES_HPP